const projectData = [
    {
        index: 1,
        title: "현대백화점 본점 주차장캐노피",
        category: "Public",
        location: "seoul, Korea",
        period: "Ongoing",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_1.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design strategy both in macro and micro aspect comes from the advantage of this exposed corner; ",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 2,
        title: "청라 더카운티 단독주택",
        location: "seoul, Korea",
        category: "Residential",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_2.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from th",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. ",
        images: [
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_4.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 3,
        title: "“소통의 장”, 성북동 게스트하우스",
        location: "seoul, Korea",
        category: "Commercial+Office / Cultural",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_3.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design straict grid of the facade. Also, west corner of the first floor makes a dialogue with the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_4.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_5.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 4,
        title: "현대백화점 본점 주차장캐노피",
        location: "seoul, Korea",
        category: "Commercial+Office",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_4.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design strateing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_4.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 5,
        title: "이태원동 단독주택",
        location: "seoul, Korea",
        category: "Exhibition",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_5.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent buildoth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_5.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 6,
        title: "수퍼빈 화성공장",
        location: "seoul, Korea",
        category: "Commercial+Office / Interior",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_6.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to thend micro aspect comes from the advantage of this exposed corner; strategizing the depth in its volume and in the facade detail. Respecting the facade/window arrangement in a grid manner of the neighborhood, the pilaster plays a key role in vitalizing the gesture of the building. A half of each 2ft-wide pilaster is tapered by 45 degrees, and the direction of tapering is inconsistent. This breaks a rather strict grid of the facade. Also, west corner of the first floor makes a dialogue with the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 7,
        title: "SKT타워 부회장 집무실",
        location: "seoul, Korea",
        category: "Public",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_7.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent bulows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 8,
        title: "현대백화점 본점 주차장캐노피",
        category: "Public",
        location: "seoul, Korea",
        period: "Ongoing",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_1.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent ith the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 9,
        title: "청라 더카운티 단독주택",
        location: "seoul, Korea",
        category: "Residential",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_2.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design strategy both in macro and micro aspect comes from the advantage of this exposed cornerhe sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 10,
        title: "“소통의 장”, 성북동 게스트하우스",
        location: "seoul, Korea",
        category: "Commercial+Office / Cultural",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_3.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 11,
        title: "현대백화점 본점 주차장캐노피",
        location: "seoul, Korea",
        category: "Commercial+Office",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_4.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent builllows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 12,
        title: "이태원동 단독주택",
        location: "seoul, Korea",
        category: "Exhibition",
        period: "2018",
        status: "Ongoing",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_5.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent buue with the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 13,
        title: "수퍼빈 화성공장",
        location: "seoul, Korea",
        category: "Commercial+Office / Interior",
        period: "2017",
        program: "HQ",
        status: "completed",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_6.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west ing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 14,
        title: "SKT타워 부회장 집무실",
        location: "seoul, Korea",
        category: "Public",
        period: "2016",
        program: "HQ",
        status: "completed",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_7.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design stratews a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 15,
        title: "현대백화점 본점 주차장캐노피",
        category: "Public",
        location: "seoul, Korea",
        period: "Ongoing",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_1.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design strategy both in macro and micro aspect comes from the advantage of this exposed corner; ",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 16,
        title: "청라 더카운티 단독주택",
        location: "seoul, Korea",
        category: "Residential",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_2.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from th",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. ",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 17,
        title: "“소통의 장”, 성북동 게스트하우스",
        location: "seoul, Korea",
        category: "Commercial+Office / Cultural",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_3.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design straict grid of the facade. Also, west corner of the first floor makes a dialogue with the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 18,
        title: "현대백화점 본점 주차장캐노피",
        location: "seoul, Korea",
        category: "Commercial+Office",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_4.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design strateing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 19,
        title: "이태원동 단독주택",
        location: "seoul, Korea",
        category: "Exhibition",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_5.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent buildoth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 20,
        title: "수퍼빈 화성공장",
        location: "seoul, Korea",
        category: "Commercial+Office / Interior",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_6.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to thend micro aspect comes from the advantage of this exposed corner; strategizing the depth in its volume and in the facade detail. Respecting the facade/window arrangement in a grid manner of the neighborhood, the pilaster plays a key role in vitalizing the gesture of the building. A half of each 2ft-wide pilaster is tapered by 45 degrees, and the direction of tapering is inconsistent. This breaks a rather strict grid of the facade. Also, west corner of the first floor makes a dialogue with the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 21,
        title: "SKT타워 부회장 집무실",
        location: "seoul, Korea",
        category: "Public",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_7.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent bulows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 22,
        title: "현대백화점 본점 주차장캐노피",
        category: "Public",
        location: "seoul, Korea",
        period: "Ongoing",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_1.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent ith the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 23,
        title: "청라 더카운티 단독주택",
        location: "seoul, Korea",
        category: "Residential",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_2.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design strategy both in macro and micro aspect comes from the advantage of this exposed cornerhe sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 24,
        title: "“소통의 장”, 성북동 게스트하우스",
        location: "seoul, Korea",
        category: "Commercial+Office / Cultural",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_3.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 25,
        title: "현대백화점 본점 주차장캐노피",
        location: "seoul, Korea",
        category: "Commercial+Office",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_4.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent builllows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 26,
        title: "이태원동 단독주택",
        location: "seoul, Korea",
        category: "Exhibition",
        period: "2018",
        status: "Ongoing",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_5.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent buue with the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 27,
        title: "수퍼빈 화성공장",
        location: "seoul, Korea",
        category: "Commercial+Office / Interior",
        period: "2017",
        program: "HQ",
        status: "completed",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_6.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west ing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 28,
        title: "SKT타워 부회장 집무실",
        location: "seoul, Korea",
        category: "Public",
        period: "2016",
        program: "HQ",
        status: "completed",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_7.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design stratews a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 29,
        title: "현대백화점 본점 주차장캐노피",
        category: "Public",
        location: "seoul, Korea",
        period: "Ongoing",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_1.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design strategy both in macro and micro aspect comes from the advantage of this exposed corner; ",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 30,
        title: "청라 더카운티 단독주택",
        location: "seoul, Korea",
        category: "Residential",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_2.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from th",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. ",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 31,
        title: "“소통의 장”, 성북동 게스트하우스",
        location: "seoul, Korea",
        category: "Commercial+Office / Cultural",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_3.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design straict grid of the facade. Also, west corner of the first floor makes a dialogue with the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 32,
        title: "현대백화점 본점 주차장캐노피",
        location: "seoul, Korea",
        category: "Commercial+Office",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_4.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design strateing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 33,
        title: "이태원동 단독주택",
        location: "seoul, Korea",
        category: "Exhibition",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_5.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent buildoth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 34,
        title: "수퍼빈 화성공장",
        location: "seoul, Korea",
        category: "Commercial+Office / Interior",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_6.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to thend micro aspect comes from the advantage of this exposed corner; strategizing the depth in its volume and in the facade detail. Respecting the facade/window arrangement in a grid manner of the neighborhood, the pilaster plays a key role in vitalizing the gesture of the building. A half of each 2ft-wide pilaster is tapered by 45 degrees, and the direction of tapering is inconsistent. This breaks a rather strict grid of the facade. Also, west corner of the first floor makes a dialogue with the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 35,
        title: "SKT타워 부회장 집무실",
        location: "seoul, Korea",
        category: "Public",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_7.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent bulows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 36,
        title: "현대백화점 본점 주차장캐노피",
        category: "Public",
        location: "seoul, Korea",
        period: "Ongoing",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_1.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent ith the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 37,
        title: "청라 더카운티 단독주택",
        location: "seoul, Korea",
        category: "Residential",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_2.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design strategy both in macro and micro aspect comes from the advantage of this exposed cornerhe sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 38,
        title: "“소통의 장”, 성북동 게스트하우스",
        location: "seoul, Korea",
        category: "Commercial+Office / Cultural",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_3.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 39,
        title: "현대백화점 본점 주차장캐노피",
        location: "seoul, Korea",
        category: "Commercial+Office",
        period: "2016-2018",
        status: "completed",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_4.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent builllows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 40,
        title: "이태원동 단독주택",
        location: "seoul, Korea",
        category: "Exhibition",
        period: "2018",
        status: "Ongoing",
        program: "HQ",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_5.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent buue with the existing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 41,
        title: "수퍼빈 화성공장",
        location: "seoul, Korea",
        category: "Commercial+Office / Interior",
        period: "2017",
        program: "HQ",
        status: "completed",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_6.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west ing adjacent neighbor and the chamfered east corner of the top floor allows a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
    {
        index: 42,
        title: "SKT타워 부회장 집무실",
        location: "seoul, Korea",
        category: "Public",
        period: "2016",
        program: "HQ",
        status: "completed",
        floor: "5F+1BF",
        area: "9,000sf",
        thumburl: "../static/images/img_7.png",
        info_en: "The site of 18ft by 100ft is located on the 130th street between Park and Madison Avenue in East Harlem. Buildings in this row uniquely does not line up at the lot line. The adjacent building to the west aligns its facade with the lot line. However the one to the east sits at 7ft set back from the lot line, which allows an exposed corner. The design stratews a smooth transition to the adjacent building of the east and opens up to the sky.",
        info_kr: "봄바람을 있는 얼마나 남는 피어나는 얼마나 우리는 구하지 이것이다. 천하를 꽃이 싹이 그와 교향악이다. 웅대한 꽃 그들은 이상의 심장은 보내는 사막이다. 이 이상이 역사를 어디 크고 못하다 찾아 사라지지 약동하다. 사랑의 피는 우리의 꽃이 무엇을 가지에 능히 스며들어 봄바람이다. 어디 살 목숨이 무엇이 바이며, 끝까지 노년에게서 풀이 간에 것이다. 그러므로 황금시대의 미묘한 커다란 사막이다. 지혜는 이상, 용기가 것이 몸이 예수는 많이 기쁘며, 약동하다. 구하지 찬미를 구하지 끝에 행복스럽고 곳이 사는가 황금시대의 같은 사막이다. 용감하고 대한 그것을 주며, 이것이다. 같이 밥을 반짝이는 원질이 것이다.",
        images: [
            {
                url: "../static/images/img_1.png",
                alt: "../static/images/img_1.png",
            },
            {
                url: "../static/images/img_2.png",
                alt: "../static/images/img_2.png",
            },
            {
                url: "../static/images/img_3.png",
                alt: "../static/images/img_3.png",
            },
        ],
    },
];

export default projectData;
